from aws_cdk import (
    Stack,
    aws_s3 as s3,
    aws_s3_deployment as s3_deployment,
    aws_cloudfront as cloudfront,
    aws_iam as iam,
    RemovalPolicy,
    Duration,
    CfnOutput,
)
from constructs import Construct


class ServerlessSpaCdkStack(Stack):

    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # Create S3 bucket for static website hosting
        # Note: Bucket name is auto-generated by CDK to ensure global uniqueness
        website_bucket = s3.Bucket(
            self, "WebsiteBucket",
            # Removed explicit bucket_name to allow CDK to generate unique name
            # This prevents naming conflicts as S3 bucket names must be globally unique
            website_index_document="index.html",
            website_error_document="index.html",  # For SPA routing
            public_read_access=False,  # CloudFront will access via OAC
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            removal_policy=RemovalPolicy.DESTROY,  # For dev/testing - change for prod
            auto_delete_objects=True,  # For dev/testing - change for prod
            encryption=s3.BucketEncryption.S3_MANAGED,
            versioned=False,
        )

        # Create Origin Access Control for CloudFront using CfnOriginAccessControl
        origin_access_control = cloudfront.CfnOriginAccessControl(
            self, "OriginAccessControl",
            origin_access_control_config=cloudfront.CfnOriginAccessControl.OriginAccessControlConfigProperty(
                name=f"{construct_id}-OAC",
                origin_access_control_origin_type="s3",
                signing_behavior="always",
                signing_protocol="sigv4",
            )
        )

        # Create CloudFront distribution using CfnDistribution for full control
        # When using OAC with S3, we MUST specify S3OriginConfig (CloudFront requirement)
        # Use empty string for OriginAccessIdentity when using OAC (OAC replaces OAI)
        cfn_distribution = cloudfront.CfnDistribution(
            self, "CloudFrontDistribution",
            distribution_config=cloudfront.CfnDistribution.DistributionConfigProperty(
                default_root_object="index.html",
                origins=[
                    cloudfront.CfnDistribution.OriginProperty(
                        id="S3Origin",
                        domain_name=website_bucket.bucket_regional_domain_name,
                        origin_access_control_id=origin_access_control.attr_id,
                        # Required: S3OriginConfig must be specified (CloudFront validation)
                        # When using OAC, set OriginAccessIdentity to empty string
                        s3_origin_config=cloudfront.CfnDistribution.S3OriginConfigProperty(
                            origin_access_identity="",  # Empty when using OAC
                        ),
                    )
                ],
                default_cache_behavior=cloudfront.CfnDistribution.DefaultCacheBehaviorProperty(
                    target_origin_id="S3Origin",
                    viewer_protocol_policy="redirect-to-https",
                    allowed_methods=["GET", "HEAD"],
                    cached_methods=["GET", "HEAD"],
                    compress=True,
                    cache_policy_id=cloudfront.CachePolicy.CACHING_OPTIMIZED.cache_policy_id,
                ),
                enabled=True,
                price_class="PriceClass_100",  # US, Canada, Europe
                http_version="http2and3",
                ipv6_enabled=True,
                custom_error_responses=[
                    cloudfront.CfnDistribution.CustomErrorResponseProperty(
                        error_code=403,
                        response_code=200,
                        response_page_path="/index.html",
                        error_caching_min_ttl=300,
                    ),
                    cloudfront.CfnDistribution.CustomErrorResponseProperty(
                        error_code=404,
                        response_code=200,
                        response_page_path="/index.html",
                        error_caching_min_ttl=300,
                    ),
                ],
            )
        )

        # Grant CloudFront access to the bucket via bucket policy
        bucket_policy = iam.PolicyStatement(
            effect=iam.Effect.ALLOW,
            principals=[iam.ServicePrincipal("cloudfront.amazonaws.com")],
            actions=["s3:GetObject"],
            resources=[f"{website_bucket.bucket_arn}/*"],
            conditions={
                "StringEquals": {
                    "AWS:SourceArn": f"arn:aws:cloudfront::{self.account}:distribution/{cfn_distribution.attr_id}"
                }
            }
        )
        website_bucket.add_to_resource_policy(bucket_policy)

        # Deploy frontend files to S3
        # Note: BucketDeployment requires a Distribution object, not CfnDistribution
        # We'll deploy without auto-invalidation, but you can manually invalidate cache if needed:
        # aws cloudfront create-invalidation --distribution-id <id> --paths "/*"
        s3_deployment.BucketDeployment(
            self, "DeployWebsite",
            sources=[s3_deployment.Source.asset("frontend")],
            destination_bucket=website_bucket,
            # Cannot use distribution here with CfnDistribution
            # Cache will be invalidated on subsequent deployments via CDK
        )

        # Outputs
        CfnOutput(
            self, "CloudFrontURL",
            value=f"https://{cfn_distribution.attr_domain_name}",
            description="CloudFront Distribution URL",
        )

        CfnOutput(
            self, "DistributionId",
            value=cfn_distribution.attr_id,
            description="CloudFront Distribution ID",
        )

        CfnOutput(
            self, "BucketName",
            value=website_bucket.bucket_name,
            description="S3 Bucket Name",
        )